### ISSUE TITLE
Ignore `_build/` and `node_modules/`

### ISSUE THREAD

**Issue by FredrikAugust** [mysticmode/LibreRead#2]
To make the repo a little bit smaller, leads to faster uploading/downloading.

See example here: https://github.com/phoenixframework/phoenix/blob/master/.gitignore

**Comment by mysticmode** [comment]
@FredrikAugust Yes, that has to be done. Can you come on Google chat? I'll send a request.

**Comment by mysticmode** [comment]
I updated .gitignore
https://github.com/mysticmode/LibreRead/commit/60f00ab1b846fc44226525ac588e757969100775
